AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

# Test files have longer methods due to fixture setup and assertions
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'test/**/*'
